### ISSUE TITLE
Outdated Connector Documentation

### ISSUE THREAD

**Issue by ajanthan** [wso2-extensions/esb-inbound-salesforce#13]
**Description:**

The [salesforce inbound endpoint connector documentation](https://docs.wso2.com/display/ESBCONNECTORS/Configuring+Salesforce+Streaming+Inbound+Endpoint+Operations) is outdated. It is missing some critical information such as 

- connection.salesforce.packageVersion ->35->37
- connection.salesforce.salesforceObject -> format changed(<topic name>->/topic/<topic name>)

Without these changes, the connector doesn't work. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/docs-mi/issues/785
